In [1]:
import pandas as pd

In [8]:
df_all_features = pd.read_excel(r"\\zkh\appdata\RTDicom\Projectline_HNC_modelling\Users\Daniel MacRae\MDACC_database-clean_Daniel.xlsx")
df_all_features['PatientID'] = df_all_features['newID'].astype(str).str.zfill(10)
df_all_features.head(5)

,ID,newID,AGE1,CT_Artefact,Year,BaselineWeight,x3_6MonthsWeight,x12MonthsWeight,Sex,ConcurrentTherapyIncludingChemoOrTargetTherapy,...,Submandibular_RDmean_DLC,SupraglotticDmean_DLC,BrainDmean_DLC,MandibleDmean_DLC,BrainstemDmean_DLC,Submandibular_Dmean_DLC,Parotid_Dmean,CT_Artefact.1,P16,PatientID
0,STIEFEL_213,3205005928,42.0,2,2016,93.7,81.1,83.2,Male,Yes,...,64.169963,48.445662,6.609855,39.973550,NaN,68.210757,27.621717,2.0,Yes,3205005928
1,STIEFEL_245,1501070517,44.0,2,2016,89.0,89.3,NaN,Male,No,...,63.174532,39.468787,3.851732,35.280161,NaN,58.796209,21.227938,2.0,Yes,1501070517
2,STIEFEL_296,9156619185,46.0,2,2016,86.5,NaN,NaN,Male,Yes,...,1.528954,32.259217,1.529044,19.334711,NaN,31.145917,27.856123,2.0,Yes,9156619185
3,STIEFEL_8,3028333367,47.0,2,2017,90.8,NaN,NaN,Male,Yes,...,47.833053,66.334379,1.891060,37.474272,NaN,61.190573,21.394946,2.0,Unknown,3028333367
4,STIEFEL_122,2894996073,48.0,2,2016,91.4,77.0,75.3,Female,Yes,...,49.418926,71.602003,4.352839,37.929654,NaN,61.729878,28.798207,2.0,Yes,2894996073

In [12]:


column_name_dict = {'Parotid_LDmean' : 'Parotid_L_meandose',
                    	'Parotid_RDmean'    : 'Parotid_R_meandose',}

In [13]:
df_test_set = pd.read_csv(r"\\zkh\appdata\RTDicom\Projectline_HNC_modelling\Users\Daniel MacRae\1. MultiTox_HNC\DL_NTCP_Multitox\datasets\MDACC_dataset\MDACC_stratified_sampling_test.csv", delimiter=';')
df_test_set['PatientID'] = df_test_set['PatientID'].astype(str).str.zfill(10)
df_test_set.head(5)

,PatientID,Age,Sex,Loctum2,Photons,T_stage,N_stage,WHO,Smoking,CT+C,...,Xerostomia_M12_Nogal_Heel_erg,Dysphagia_BSL_Grade0_1,Dysphagia_BSL_Grade2,Dysphagia_BSL_Grade3_4,Dysphagia_M06_Grade0_1,Dysphagia_M06_Grade2,Dysphagia_M06_Grade3_4,Dysphagia_M12_Grade0_1,Dysphagia_M12_Grade2,Dysphagia_M12_Grade3_4
0,1019236881,0.55,1,Pharynx,1,T3,N2,0,0,0,...,1,0,0,1,0,0,1,0,0,0
1,1022096596,0.64,1,Pharynx,1,T3,N1,0,0,0,...,1,0,0,1,1,0,0,1,0,0
2,1027008628,0.57,1,Pharynx,1,T1,N1,0,0,0,...,1,1,0,0,1,0,0,0,0,0
3,1029341402,0.55,1,Unknown primary,1,T0,N2,0,0,0,...,0,1,0,0,1,0,0,1,0,0
4,1041973121,0.59,1,Pharynx,0,T1,N2,0,0,0,...,1,1,0,0,0,0,1,1,0,0

In [ ]:
df_all_features_parotid = df_all_features[['PatientID', 'Parotid_LDmean', 'Parotid_RDmean']].copy()



df_new_test_set = df_test_set.merge(df_all_features_parotid, on='PatientID', how='left')

In [20]:
df_new_test_set = df_new_test_set.rename(columns=column_name_dict)
df_new_test_set = df_new_test_set.rename(columns=bsl_to_w01_dict)
df_new_test_set.to_csv(r"\\zkh\appdata\RTDicom\Projectline_HNC_modelling\Users\Daniel MacRae\1. MultiTox_HNC\DL_NTCP_Multitox\datasets\MDACC_dataset\MDACC_stratified_sampling_test_CITOR.csv", sep=';', index=False)

In [19]:
bsl_to_w01_dict = {col: col.replace('BSL', 'W01') for col in df_new_test_set.columns if 'BSL' in col}
bsl_to_w01_dict

{'Xerostomia_BSL': 'Xerostomia_W01',
 'Aspiration_BSL': 'Aspiration_W01',
 'Sticky_BSL': 'Sticky_W01',
 'Taste_BSL': 'Taste_W01',
 'Dysphagia_BSL': 'Dysphagia_W01',
 'Aspiration_BSL_Een_beetje': 'Aspiration_W01_Een_beetje',
 'Aspiration_BSL_Heel_erg': 'Aspiration_W01_Heel_erg',
 'Aspiration_BSL_Helemaal_niet': 'Aspiration_W01_Helemaal_niet',
 'Aspiration_BSL_Nogal': 'Aspiration_W01_Nogal',
 'Aspiration_BSL_Nogal_Heel_erg': 'Aspiration_W01_Nogal_Heel_erg',
 'Sticky_BSL_Een_beetje': 'Sticky_W01_Een_beetje',
 'Sticky_BSL_Heel_erg': 'Sticky_W01_Heel_erg',
 'Sticky_BSL_Helemaal_niet': 'Sticky_W01_Helemaal_niet',
 'Sticky_BSL_Nogal': 'Sticky_W01_Nogal',
 'Sticky_BSL_Nogal_Heel_erg': 'Sticky_W01_Nogal_Heel_erg',
 'Taste_BSL_Een_beetje': 'Taste_W01_Een_beetje',
 'Taste_BSL_Heel_erg': 'Taste_W01_Heel_erg',
 'Taste_BSL_Helemaal_niet': 'Taste_W01_Helemaal_niet',
 'Taste_BSL_Nogal': 'Taste_W01_Nogal',
 'Taste_BSL_Nogal_Heel_erg': 'Taste_W01_Nogal_Heel_erg',
 'Xerostomia_BSL_Een_beetje': 'Xerostomia_W01_Een_beetje',
 'Xerostomia_BSL_Heel_erg': 'Xerostomia_W01_Heel_erg',
 'Xerostomia_BSL_Helemaal_niet': 'Xerostomia_W01_Helemaal_niet',
 'Xerostomia_BSL_Nogal': 'Xerostomia_W01_Nogal',
 'Xerostomia_BSL_Nogal_Heel_erg': 'Xerostomia_W01_Nogal_Heel_erg',
 'Dysphagia_BSL_Grade0_1': 'Dysphagia_W01_Grade0_1',
 'Dysphagia_BSL_Grade2': 'Dysphagia_W01_Grade2',
 'Dysphagia_BSL_Grade3_4': 'Dysphagia_W01_Grade3_4'}