In [33]:
import os 
import pandas as pd
import numpy as np

In [34]:
dir = r"C:\Users\S.P.M. de Vette\OneDrive - UMCG\Desktop\pred_RT_results\CT_artefact_new\ResNet10\ensemble_predictions.csv"

df_ens_preds = pd.read_csv(dir, delimiter=';')
df_ens_preds["PatientID"] = df_ens_preds["PatientID"].astype(str).str.zfill(7)
df_ens_preds

    PatientID  Mode  CT_Artefact_binarised_pred  CT_Artefact_binarised_true
0     0052277  test                    0.388946                         0.0
1     0066593  test                    0.363372                         1.0
2     0092560  test                    0.077787                         0.0
3     0163517  test                    0.100759                         0.0
4     0213240  test                    0.093473                         0.0
..        ...   ...                         ...                         ...
213   9653665  test                    0.028558                         0.0
214   9715913  test                    0.082963                         0.0
215   9878177  test                    0.094605                         0.0
216   9949620  test                    0.951746                         1.0
217   9977441  test                    0.091586                         0.0

[218 rows x 4 columns]

In [35]:
df_dataset2 = pd.read_csv(r"C:\Users\S.P.M. de Vette\OneDrive - UMCG\Documents\DL_NTCP_Multitox\datasets\MT_dataset\stratified_sampling_test_542_2.csv", delimiter=';')
df_dataset2["PatientID"] = df_dataset2["PatientID"].astype(str).str.zfill(7)
df_dataset2 = df_dataset2[["PatientID", 'CT_Artefact', 'CT_Artefact_binarised']]
df_ens_preds = df_ens_preds.merge(df_dataset2, on="PatientID", how="left")

In [36]:
metal_artefact_patients = df_ens_preds[df_ens_preds['CT_Artefact_binarised'] == 1]
no_metal_artefact_patients = df_ens_preds[df_ens_preds['CT_Artefact_binarised'] == 0]

In [38]:
no_metal_artefact_patients_sorted = no_metal_artefact_patients.sort_values(by='CT_Artefact_binarised_pred', ascending=False)
no_metal_artefact_patients_sorted.head(10)

,PatientID,Mode,CT_Artefact_binarised_pred,CT_Artefact_binarised_true,CT_Artefact,CT_Artefact_binarised
95,2241472,test,0.937854,0.0,0,0
133,5222055,test,0.916827,0.0,0,0
24,0777661,test,0.563150,0.0,0,0
176,7709085,test,0.559822,0.0,0,0
36,0957905,test,0.417233,0.0,0,0
183,8040993,test,0.389780,0.0,0,0
0,0052277,test,0.388946,0.0,0,0
142,5775322,test,0.375883,0.0,0,0
172,7610624,test,0.352274,0.0,0,0
33,0919221,test,0.342969,0.0,0,0

In [40]:
metal_artefact_patients_sorted = metal_artefact_patients.sort_values(by='CT_Artefact_binarised_pred', ascending=True)
metal_artefact_patients_sorted.head(20)

,PatientID,Mode,CT_Artefact_binarised_pred,CT_Artefact_binarised_true,CT_Artefact,CT_Artefact_binarised
91,2188849,test,0.064817,1.0,1,1
77,2103749,test,0.112800,1.0,1,1
164,7191904,test,0.116309,1.0,1,1
73,2080643,test,0.121045,1.0,1,1
187,8293031,test,0.132995,1.0,1,1
20,0665360,test,0.133542,1.0,1,1
68,2038542,test,0.143321,1.0,1,1
120,4623812,test,0.148549,1.0,1,1
209,9415901,test,0.152630,1.0,1,1
162,7137600,test,0.169509,1.0,1,1
192,8624550,test,0.186373,1.0,1,1
26,0810853,test,0.197184,1.0,1,1
141,5720176,test,0.239491,1.0,1,1
121,4626308,test,0.249060,1.0,2,1
67,2027942,test,0.254843,1.0,1,1
208,9325321,test,0.341451,1.0,1,1
1,0066593,test,0.363372,1.0,1,1
211,9586209,test,0.432681,1.0,1,1
62,1870106,test,0.442198,1.0,1,1
92,2199947,test,0.465478,1.0,1,1

In [32]:
from sklearn.metrics import accuracy_score, roc_auc_score

df_ens_preds['CT_Artefact_binarised_2'] = df_ens_preds['CT_Artefact'] >= 2

# Calculate accuracy
accuracy = accuracy_score(df_ens_preds['CT_Artefact_binarised_2'], df_ens_preds['CT_Artefact_pred'].round())
print(f'Accuracy: {accuracy}')

# Calculate AUC
auc = roc_auc_score(df_ens_preds['CT_Artefact_binarised_2'], df_ens_preds['CT_Artefact_pred'])
print(f'AUC: {auc}')

Accuracy: 0.8798076923076923
AUC: 0.9765063907486305