In [11]:
import pandas as pd

In [18]:
df_dataset = pd.read_csv("/home/macraedc/data/MT_dataset_with_all_structs.csv", sep=';')
df_dataset

,PatientID,Split,DB,RTSTART,Geslacht,Leeftijd,Loctum,Loctum2,Technique,Inplancode,...,N1,N2,N3,"Roken_Ja, in verleden","Roken_Ja, nog steeds",Roken_Nee,Chemoradiation,Bioradiation,Concurrent_Chemo_or_Bioradiation,Protons
0,10125,train_val,REDCAP,2018-07-02,0,0.55,Palatum molle + uvula,Pharynx,VMAT,HH 35 6x-F,...,0,0,0,1,0,0,0,0,0,0
1,10152,train_val,REDCAP,2013-08-12,1,0.59,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,HH IMRT 35 5x PET_CT(CBCT),...,0,1,0,0,1,0,1,0,1,0
2,10279,train_val,CITOR143,2017-10-23,1,0.67,Supraglottisch,Larynx,VMAT,HH VMAT 35 5x CBCT,...,0,1,0,1,0,0,1,0,1,0
3,10348,test,CITOR750,2009-05-25,1,0.81,Glottisch,Larynx,3D-CRT,-1,...,0,0,0,0,0,1,0,0,0,0
4,10619,train_val,CITOR750,2012-08-13,1,0.64,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1368,99777,train_val,RECAP,2023-04-12,1,0.71,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH 35 5pw-P,...,0,1,0,1,0,0,0,0,0,1
1369,99798,train_val,REDCAP,2019-07-24,1,0.71,Supraglottisch,Larynx,VMAT,HH 35 5x-F,...,0,1,0,1,0,0,0,0,0,0
1370,99820,train_val,CITOR750,2010-01-11,1,0.76,Hypopharynxachterwand (vanaf nivo vallecula),Pharynx,IMRT,-1,...,1,0,0,1,0,0,0,1,1,0
1371,99870,train_val,RECAP,2023-07-05,1,0.60,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH 35 5pw-P,...,0,1,0,1,0,0,0,0,0,1
1372,99917,train_val,RECAP,2022-02-09,0,0.58,Nasopharynx,Pharynx,Protons,HH-Primair-Standaard,...,0,0,0,1,0,0,0,0,0,1

In [19]:
import numpy as np

df_OS_data = df_dataset[["PatientID", 'Split', 'Leeftijd', 'Protons', 'Xerostomia_M06', 'Dysphagia_M06']]
df_OS_data["OS_event"] = (df_OS_data["Leeftijd"] >= df_OS_data["Leeftijd"].quantile(0.6)).astype(int)
df_OS_data

num_to_modify = int(0.1 * len(df_OS_data))
random_indices = np.random.choice(df_OS_data.index, size=num_to_modify, replace=False)
df_OS_data.loc[random_indices, "OS_event"] = -1

df_OS_data["OS_months"] = 0
mask_0 = df_OS_data["OS_event"] == 0
mask_1 = df_OS_data["OS_event"] == 1
mask_2 = df_OS_data["OS_event"] == -1
df_OS_data.loc[mask_0, "OS_days"] = np.random.randint(0, 2000, size=mask_0.sum())
df_OS_data.loc[mask_1, "OS_days"] = np.random.randint(0, 2000, size=mask_1.sum())
df_OS_data.loc[mask_2, "OS_days"] = np.random.randint(-1, 0, size=mask_2.sum())

df_OS_data["OS_months"] = df_OS_data["OS_days"] // 30

/home/macraedc/tmp/ipykernel_481573/601220155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_OS_data["OS_event"] = (df_OS_data["Leeftijd"] >= df_OS_data["Leeftijd"].quantile(0.6)).astype(int)
/home/macraedc/tmp/ipykernel_481573/601220155.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_OS_data["OS_months"] = 0
/home/macraedc/tmp/ipykernel_481573/601220155.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_OS_data.loc[mask_0, "OS_days"] = np.random.randint(0, 2000, size=mask_0.sum())
/home/macraedc/tmp/ipykernel_481573/601220155.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_OS_data["OS_months"] = df_OS_data["OS_days"] // 30

In [20]:
df_OS_data

,PatientID,Split,Leeftijd,Protons,Xerostomia_M06,Dysphagia_M06,OS_event,OS_months,OS_days
0,10125,train_val,0.55,0,1,0,0,5.0,167.0
1,10152,train_val,0.59,0,0,0,0,0.0,28.0
2,10279,train_val,0.67,0,1,0,1,54.0,1644.0
3,10348,test,0.81,0,0,0,1,62.0,1870.0
4,10619,train_val,0.64,0,0,0,0,48.0,1450.0
...,...,...,...,...,...,...,...,...,...
1368,99777,train_val,0.71,1,1,0,1,35.0,1073.0
1369,99798,train_val,0.71,0,0,0,1,13.0,390.0
1370,99820,train_val,0.76,0,1,1,1,65.0,1978.0
1371,99870,train_val,0.60,1,-1,0,0,50.0,1517.0
1372,99917,train_val,0.58,1,0,0,-1,-1.0,-1.0

In [21]:
df_OS_data.to_csv("/home/macraedc/data/fake_OS_data.csv", sep=';', index=False)

In [12]:
df_OS_data

,PatientID,Split,Leeftijd,Protons,Xerostomia_M06,OS_event,OS_months
0,10125,train_val,0.55,0,1,0,535
1,10152,train_val,0.59,0,0,0,215
2,10279,train_val,0.67,0,1,0,735
3,10348,test,0.81,0,0,1,5
4,10619,train_val,0.64,0,0,0,67
...,...,...,...,...,...,...,...
1368,99777,train_val,0.71,1,1,0,96
1369,99798,train_val,0.71,0,0,0,1269
1370,99820,train_val,0.76,0,1,1,16
1371,99870,train_val,0.60,1,-1,0,758
1372,99917,train_val,0.58,1,0,0,1151

In [ ]:
arr1 = np.random.rand(3, 2)
arr2 = np.random.rand(2, 2)
arr3 = np.empty((0,2))

total_arr = np.concatenate([arr1, arr2, arr3], axis=0)

df_total = pd.DataFrame(total_arr, columns=["col1", "col2"])
df_total

In [28]:
label_columns= ["Xero", ('OS_days', 'OS_event')]
flattened_label_columns = []
for col in label_columns:
    if isinstance(col, (list, tuple)):
        flattened_label_columns.extend(col)
    else:
        flattened_label_columns.append(col)
label_columns = flattened_label_columns
label_columns

['Xero', 'OS_days', 'OS_event']

In [44]:
label_COLUMNS= ["Xero", ('OS_days', 'OS_event')]


for label_column_names in label_COLUMNS:
    label_column_names = [label_column_names] if isinstance(label_column_names, str) else label_column_names
    print(label_column_names)
    label_columns = ['{}_true'.format(x) for x in label_column_names]
    print(label_columns)

['Xero']
['Xero_true']
('OS_days', 'OS_event')
['OS_days_true', 'OS_event_true']

In [129]:
endpoint_list = ['Xerostomia_M06', 'Dysphagia_M06', 'OS']
endpoint_types_list = ['Binary', 'Binary', "Event"]

# from collections import defaultdict


# endpoint_type_groups = defaultdict(list)
# for endpoint, endpoint_type in zip(endpoint_list, endpoint_types_list):
#     print(endpoint_type)
#     endpoint_type_groups[endpoint_type].append(endpoint)
    
# endpoint_type_groups = dict(endpoint_type_groups)
# endpoint_type_groups

In [130]:
from collections import defaultdict


def seperate_endpoint_indicies(endpoint_list, endpoint_types_list):
    endpoint_type_groups_indicies = defaultdict(list)
    endpoint_type_groups_names = defaultdict(list)


    idx = 0
    for endpoint, endpoint_type in zip(endpoint_list, endpoint_types_list):
    #print(endpoint_type)
        if 'Event' == endpoint_type:
            endpoint_type_groups_indicies[endpoint_type].append([idx, idx + 1])
        #endpoint_type_groups_indicies[endpoint_type].append(idx + 1)
        
            endpoint_type_groups_names[endpoint_type].append(endpoint_list[idx])
        #endpoint_type_groups_names[endpoint_type].append(endpoint_list[idx + 1])

            idx += 2
        else:
            endpoint_type_groups_indicies[endpoint_type].append(idx)
            endpoint_type_groups_names[endpoint_type].append(endpoint_list[idx])
            idx += 1

    endpoint_type_groups_indicies = dict(endpoint_type_groups_indicies)
    endpoint_type_groups_names = dict(endpoint_type_groups_names)

    return endpoint_type_groups_indicies,endpoint_type_groups_names


endpoint_type_groups_indicies, endpoint_type_groups_names = seperate_endpoint_indicies(endpoint_list, endpoint_types_list)

endpoint_type_groups_indicies


endpoint_type_groups_names

{'Binary': ['Xerostomia_M06', 'Dysphagia_M06'], 'Event': ['OS']}

In [133]:
endpoint_type_groups_indicies

{'Binary': [0, 1], 'Event': [[2, 3]]}

In [131]:
endpoint_type_groups_indicies['Binary']

[0, 1]

In [132]:
binary_endpoints = endpoint_type_groups_names['Binary']
binary_endpoints

['Xerostomia_M06', 'Dysphagia_M06']

In [18]:
import torch

batch_size = 8

endpoint_tensor_dict = {
    'Dysphagia_M06': torch.randn(batch_size, 1),
    'Xerostomia_M06': torch.randn(batch_size, 1),
    'OS': torch.randn(batch_size, 1),
    'LRC': torch.randn(batch_size, 1),
}


# Create random binary labels for the two binary endpoints
labels_tensor = torch.randint(0, 2, (batch_size, 3)).float()

labels_tensor = torch.cat(
    [labels_tensor, 
     torch.randint(100, 200, (batch_size, 1)).float(),
     torch.randint(-1, 2, (batch_size, 1)).float(),
     torch.randint(100, 200, (batch_size, 1)).float()],
    dim=1
)

# Access multiple dictionary keys at once using a list comprehension
# binary_endpoints = endpoint_type_groups_names['Binary']
# flattened_binary_tensor = torch.cat([endpoint_tensor_dict[key] for key in binary_endpoints], dim=1)

In [26]:
import numpy as np
values = np.array(labels_tensor[:, -2:-1])

missing_val = -1
mask = ~(values == missing_val).any(axis=1)

mask

array([False, False,  True,  True, False,  True, False, False])

In [ ]:
%load_ext autoreload
%autoreload 2

from src.utils.loss_func.MultiLabel_Loss import MultiLabel_Loss
from src.config_presets.tools.get_config import get_config

config = get_config("Daniel/HNC_OS_test")


loss_function = MultiLabel_Loss(
    config=config,
    binary_loss_function=torch.nn.BCEWithLogitsLoss(reduction='none'),)

loss_function.forward(
    outputs_dict=endpoint_tensor_dict,
    labels_dict=labels_tensor
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
src/config_presets/Base_config.yaml
src/config_presets/Daniel/HNC_OS_test.yaml
src/config_presets/testMode_config.yaml
{'Binary': [0, 1], 'Event': [[2, 3], [4, 5]]}
Risk prediction shape: torch.Size([8, 2]), Labels shape: torch.Size([8, 2]), Events shape: torch.Size([8, 2])

(tensor(0.4255),
 {'Xerostomia_M06': tensor(0.6343),
  'Dysphagia_M06': tensor(0.9166),
  'OS': tensor(0.1258),
  'LRC': tensor(0.0251)})

In [177]:
config['columns']

{'labels': ['Xerostomia_M06', 'Dysphagia_M06', 'OS', 'LRC'],
 'labels_types': ['Binary', 'Binary', 'Event', 'Event'],
 'clinical_features': ['Leeftijd']}

In [178]:
labels_tensor.shape

torch.Size([4, 6])

In [195]:
y = labels_tensor[:, [-4,-2]]
y.shape

torch.Size([4, 2])

In [198]:
(y.T - y) > 0

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [197]:
y = labels_tensor[:, [-4,-2]]  # Extracting the last two columns for OS and LRC, which are Event endpoints
y
mask = torch.ones(y.shape[0], y.shape[1])

mask[(y.T - y) > 0] = 0

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [79]:
endpoint_tensor_dict

{'Dysphagia_M06': tensor([[ 0.6654],
         [-0.7166],
         [ 0.0226],
         [ 1.4679]]),
 'Xerostomia_M06': tensor([[-0.2218],
         [-1.0085],
         [ 0.7123],
         [ 1.2631]]),
 'OS': tensor([[ 0.3398],
         [ 0.9978],
         [-0.0892],
         [ 1.6741]])}